# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41bdf06a7ba218f7ebd631258a76766b8358870b4c56ed56ed4069a9f274a337693b123a34502ef4a81db9addb3cf38bcae6062c5a8cebf9362147fa60a35cbd

test:
  secret_key_base: 3ff5c53b14fc317619c0a04f0b1f305ec7b7a0b78ca39fd77767306955d6e29137130ec0143897042faac59c0f16fec67d0092b79ebcfa666052db4bb47558ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
